language: node_js
node_js:
  - 8.11.2
  - '9'
before_install:
  - |-
    if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ];
     then
        echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc;
      else
        echo "//registry.npmjs.org/:_authToken=\${NPM_INSTALL_TOKEN}" > ~/.npmrc;
    fi
  - 'git config --global url."git@github.com:".insteadOf "https://github.com/"'
  - npm i -g lsc
  - export CHROME_BIN=chromium-browser
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - lsc build web
script:
  - npm test
  - >-
    npm run coverage && cat ./test/ui/coverage/lcov.info |
    ./node_modules/coveralls/bin/coveralls.js && rm -rf ./test/ui/coverage
cache:
  directories:
    - ~/.npm
notifications:
  email: false
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^vd+.d+.d+$/
